tag_dict = {
    "E": "Verbal endings",
    "IC": "Interjection",
    "J": "Ending Particle",
    "MAG": "General Adverb",
    "MAJ": "Conjunctive adverb",
    "MM": "Determiner",
    "NA": "Unknown",
    "NNB": "Dependent noun (following nouns)",
    "NNBC": "Dependent noun",
    "NNG": "General Noun",
    "NNP": "Proper Noun",
    "NP": "Pronoun",
    "NR": "Numeral",
    "SC:Separator (· / ": ")",
    "SE": "Ellipsis",
    "SF": "Terminal punctuation (? ! .)",
    "SH": "Chinese character",
    "SL": "Foreign language",
    "SN": "Number",
    "SP": "Space",
    "SSC": "Closing brackets",
    "SSO": "Opening brackets",
    "SY": "Other symbol",
    "UNA": "Unknown",
    "UNKNOWN": "Unknown",
    "VA": "Adjective",
    "VCN": "Negative designator",
    "VCP": "Positive designator",
    "VSV": "Unknown",
    "VV": "Verb",
    "VX": "Auxiliary Verb or Adjective",
    "XPN": "Prefix",
    "XR": "Root",
    "XSA": "Adjective Suffix",
    "XSN": "Noun Suffix",
    "XSV": "Verb Suffix",
    "JKB": "?",
    "JKG": "?",
    "JX": "?",
    "EF": "?",
}